name: slick_slides
description: Create a nice looking presentations in Flutter with animations and code. Intended for techical talks and videos.
version: 0.2.1
repository: https://github.com/serverpod/slick_slides
topics:
  - presentation
  - slides

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"
  

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  audioplayers: ^5.2.1
  diff_match_patch: ^0.4.1
  syntax_highlight: ^0.3.0
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
